### ISSUE TITLE
能不能写个tabbar例子？

### ISSUE THREAD

**Issue by daizheng521** [Hanks10100/weex-vue-examples#2]
能不能写个tabbar例子？

**Comment by Hanks10100** [comment]
这个组件暂时还没对外，有些功能还在测

**Comment by py389172739** [comment]
@Hanks10100  我想问下怎么把多个vue生成多个jsbunlde文件，就是每个vue生成一个js，我想做多页面之间的跳转，但是我发现navigator组件跳转时传入的地址都是js的地址

**Comment by Hanks10100** [comment]
@py389172739 打包的时候配置多个入口，或者用多个配置文件就能生成多个 js 了。
