### ISSUE TITLE
phantom-limb无法激活input输入框

### ISSUE THREAD

**Issue by jues** [Hanks10100/weex-vue-examples#6]
浏览器打开时，将index.html中的`<script src="./assets/phantom-limb.js"></script>`注释掉可解决点击无法激活input输入框的问题

**Comment by Hanks10100** [comment]
可以去 phantom-limb 这个库提个 issue，这里我用的已经是比较新的版本了。在 PC 端看到的是模拟的效果，最好是在手机上看效果，那样最真实。
